### ISSUE TITLE
Content-Security-Policy and inline scripts

### ISSUE THREAD

**Issue by dasoe** [DirkPersky/npm-dp_cookieconsent#21]
Hello DirkPersky,

**Thank you very much for this great extension!**
For one of my customers I have to use a rather strict Content-Security-Policy, so I have to get rid of all inline scripts (or - second best - add a cryptographic nonce generated on page hit to each inline script). Is there a way of using your extension nonetheless?

Thank you and have a great day!
oe

**Comment by DirkPersky** [comment]
Have u the possebility to add a SHA crypt to your Content-Security-Policy?

https://developers.google.com/web/fundamentals/security/csp#if_you_absolutely_must_use_it_

> Using Chrome 40 or later, you can open DevTools and then reload your page. The Console tab will contain error messages with the correct sha256 hash for each of your inline scripts.

**Comment by DirkPersky** [comment]
Optinal u can use the event system to handle your code:

https://github.com/DirkPersky/npm-dp_cookieconsent#events
